-- this script does not capture the create user commands
SELECT DBMS_METADATA.GET_GRANTED_DDL('SYSTEM_GRANT','&1' )     FROM DUAL;
SELECT DBMS_METADATA.GET_GRANTED_DDL('ROLE_GRANT','&1' )     FROM DUAL;
SELECT DBMS_METADATA.GET_GRANTED_DDL('OBJECT_GRANT','&1' )     FROM DUAL;




